"""update_skill_chart_group_id_to_string

Revision ID: 0ecbce9af45e
Revises: f192df116913
Create Date: 2025-10-24 14:33:43.400748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ecbce9af45e'
down_revision = 'f192df116913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meditation_types')
    op.drop_table('calisthenics_skills')
    op.drop_table('calisthenics_progress')
    op.drop_table('calisthenics_levels')
    op.drop_table('meditation_sessions')
    op.alter_column('skill_development_charts', 'group_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_constraint(op.f('skill_development_charts_group_id_fkey'), 'skill_development_charts', type_='foreignkey')
    op.create_foreign_key(None, 'skill_development_charts', 'groups', ['group_id'], ['group_id'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'skill_development_charts', type_='foreignkey')
    op.create_foreign_key(op.f('skill_development_charts_group_id_fkey'), 'skill_development_charts', 'groups', ['group_id'], ['id'])
    op.alter_column('skill_development_charts', 'group_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('meditation_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meditation_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meditation_type_id'], ['meditation_types.id'], name=op.f('meditation_sessions_meditation_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meditation_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meditation_sessions_pkey'))
    )
    op.create_table('calisthenics_levels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('calisthenics_levels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hold_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['calisthenics_skills.id'], name='calisthenics_levels_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calisthenics_levels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('calisthenics_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_practiced', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_practice_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_level_id'], ['calisthenics_levels.id'], name=op.f('calisthenics_progress_current_level_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['calisthenics_skills.id'], name=op.f('calisthenics_progress_skill_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calisthenics_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calisthenics_progress_pkey'))
    )
    op.create_table('calisthenics_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('calisthenics_skills_pkey'))
    )
    op.create_table('meditation_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('meditation_types_pkey'))
    )
    # ### end Alembic commands ###
