"""Initial group and challenge models

Revision ID: 1937fafd42e6
Revises: 
Create Date: 2025-06-10 11:47:25.463050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1937fafd42e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_completion', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_completion', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_task_completion_date'), table_name='task_completion')
    op.drop_index(op.f('idx_task_completion_task_id'), table_name='task_completion')
    op.drop_index(op.f('idx_task_completion_user_id'), table_name='task_completion')
    op.drop_constraint(op.f('task_completion_task_id_completion_date_key'), 'task_completion', type_='unique')
    op.create_unique_constraint('uq_task_completion_date', 'task_completion', ['task_id', 'completion_date'])
    op.drop_constraint(op.f('task_completion_user_id_fkey'), 'task_completion', type_='foreignkey')
    op.drop_constraint(op.f('task_completion_task_id_fkey'), 'task_completion', type_='foreignkey')
    op.create_foreign_key(None, 'task_completion', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_completion', 'tasks', ['task_id'], ['id'])
    op.alter_column('task_notes', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('task_notes_user_id_fkey'), 'task_notes', type_='foreignkey')
    op.drop_constraint(op.f('task_notes_task_id_fkey'), 'task_notes', type_='foreignkey')
    op.create_foreign_key(None, 'task_notes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_notes', 'tasks', ['task_id'], ['id'])
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_tasks_cycle_dates'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    
    # Add password column as nullable first with length 255
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    
    # Copy password_hash to password
    op.execute("UPDATE users SET password = password_hash")
    
    # Now make password non-nullable
    op.alter_column('users', 'password', nullable=False)
    
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'password_hash')

    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('group_id', sa.Integer(), sa.ForeignKey('groups.id'), nullable=False),
        sa.Column('sender_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('recipient_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_cycle_dates'), 'tasks', ['cycle_start_date', 'cycle_end_date'], unique=False)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'task_notes', type_='foreignkey')
    op.drop_constraint(None, 'task_notes', type_='foreignkey')
    op.create_foreign_key(op.f('task_notes_task_id_fkey'), 'task_notes', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_notes_user_id_fkey'), 'task_notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_notes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('task_notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_notes', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'task_completion', type_='foreignkey')
    op.drop_constraint(None, 'task_completion', type_='foreignkey')
    op.create_foreign_key(op.f('task_completion_task_id_fkey'), 'task_completion', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_completion_user_id_fkey'), 'task_completion', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_task_completion_date', 'task_completion', type_='unique')
    op.create_unique_constraint(op.f('task_completion_task_id_completion_date_key'), 'task_completion', ['task_id', 'completion_date'])
    op.create_index(op.f('idx_task_completion_user_id'), 'task_completion', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_completion_task_id'), 'task_completion', ['task_id'], unique=False)
    op.create_index(op.f('idx_task_completion_date'), 'task_completion', ['completion_date'], unique=False)
    op.alter_column('task_completion', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_completion', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('messages')
    # ### end Alembic commands ###
