"""add group type to groups

Revision ID: c1d2e3f4g5h6
Revises: a1b2c3d4e5f6
Create Date: 2025-01-27 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_type', sa.String(length=20), nullable=False, server_default='school'))
    # Remove the server default after data migration to rely on application defaults
    op.alter_column('groups', 'group_type', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_type')
    # ### end Alembic commands ###
