"""add skill development chart table

Revision ID: f192df116913
Revises: 1937fafd42e6
Create Date: 2025-10-23 21:55:22.237204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f192df116913'
down_revision = '1937fafd42e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct order (child tables first, then parent tables)
    # Use raw SQL with IF EXISTS to handle cases where tables don't exist
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    tables_to_drop = ['calisthenics_progress', 'meditation_sessions', 'calisthenics_levels', 'calisthenics_skills', 'meditation_types']
    for table_name in tables_to_drop:
        if inspector.has_table(table_name):
            op.drop_table(table_name)
    
    # Create the skill_development_charts table (only if it doesn't exist)
    if not inspector.has_table('skill_development_charts'):
        op.create_table('skill_development_charts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('group_id', sa.Integer(), nullable=False),
            sa.Column('member_id', sa.Integer(), nullable=False),
            sa.Column('term', sa.String(length=20), nullable=False),
            sa.Column('skill_levels', sa.JSON(), nullable=False),
            sa.Column('color_scheme', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
            sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('group_id', 'member_id', 'term', name='uq_skill_chart_group_member_term')
        )
    
    # Only alter password column if it's still VARCHAR(255)
    # Check current column type first
    from sqlalchemy import text
    result = bind.execute(text("""
        SELECT data_type, character_maximum_length 
        FROM information_schema.columns 
        WHERE table_name = 'users' AND column_name = 'password'
    """))
    row = result.fetchone()
    if row and row[0] == 'character varying' and row[1] == 255:
        op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('calisthenics_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_practiced', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_practice_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_level_id'], ['calisthenics_levels.id'], name=op.f('calisthenics_progress_current_level_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['calisthenics_skills.id'], name=op.f('calisthenics_progress_skill_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calisthenics_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calisthenics_progress_pkey'))
    )
    op.create_table('meditation_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meditation_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='meditation_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('calisthenics_skills',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('calisthenics_skills_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calisthenics_skills_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('meditation_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meditation_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meditation_type_id'], ['meditation_types.id'], name=op.f('meditation_sessions_meditation_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meditation_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meditation_sessions_pkey'))
    )
    op.create_table('calisthenics_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hold_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['calisthenics_skills.id'], name=op.f('calisthenics_levels_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calisthenics_levels_pkey'))
    )
    # ### end Alembic commands ###
